Added categorized folder in data. Please review the PR.
HackerSpace-PESU/Best11-Fantasycricket pull request #12
Opened 2020-10-01 01:40 UTC by amoghku02

2020-10-01 01:41 UTC, amoghku02 commented
Issue#10: Added categorized folder in data. Please review the PR.

2020-10-01 03:02 UTC, lucasace commented
Heyy, great work a few changes though
There are some players who have played for multiple countries, Ex: Boyd Rankin who played for both England and Ireland, you have only put him under Ireland, We would like you to segregate his England matches and Ireland matches and put each of them in the respective country. There are other players like that as well, you need to ensure it doesn't cause a problem

2020-10-01 03:24 UTC, lucasace requested changes
Segregate Ireland and England matches , and create Boyd Rankin for both Ireland and England

2020-10-01 03:24 UTC, lucasace commented on data/categorized/bowl/Ireland/Boyd Rankin  (Ireland  England).csv
> +,Match_id,Score,Overs,Maidens,Wicket,Economy
This file needs to be changed , you can find the corresponding match names in allmatches.csv .

2020-10-01 03:28 UTC, lucasace requested changes

2020-10-01 03:28 UTC, lucasace commented on data/categorized/bowl/United States West Indies/Xavier Marshall  (United States  West Indies).csv
> +,Match_id,Score,Overs,Maidens,Wicket,Economy
Same problem, you can ignore USA as a country as of now, and simply change it to West Indies

2020-10-01 03:31 UTC, lucasace requested changes

2020-10-01 03:31 UTC, lucasace commented on data/categorized/bowl/Netherlands South Africa/Roelof van der Merwe  (Netherlands  South Africa).csv
> +,Match_id,Score,Overs,Maidens,Wicket,Economy
i dont think we have records for netherlands for now, just put him under South Africa for now

2020-10-01 04:05 UTC, lucasace requested changes

2020-10-01 04:05 UTC, lucasace commented on data/categorized/wk/England/Eoin Morgan  (England  Ireland).csv
> +,MATCH_ID,SCORE
Same thing as the first review

2020-10-01 04:12 UTC, lucasace requested changes

2020-10-01 04:12 UTC, lucasace commented on data/categorized/wk/New Zealand/Luke Ronchi  (New Zealand  Australia).csv
> +,MATCH_ID,SCORE
SImilar issue again

2020-10-01 04:12 UTC, lucasace commented on data/categorized/zip/England/Eoin Morgan  (England  Ireland).csv
> +matchid,date
same again

2020-10-01 04:12 UTC, lucasace commented on data/categorized/zip/Ireland/Boyd Rankin  (Ireland  England).csv
> +matchid,date
Same again

2020-10-01 04:13 UTC, lucasace commented
There are many more files like those, I think u got the general idea

2020-10-01 06:57 UTC, lucasace commented
Once you are done , do tell as there are a lot of files to review

2020-10-11 12:55 UTC, lucasace commented
Heyy, since there's no update on this for a long time, Im changing this PR to a draft. you can continue to work on it once your done, ill change it back

2020-10-14 09:22 UTC, closed without merging